ALTER TABLE accounts ADD COLUMN IF NOT EXISTS type VARCHAR(20) DEFAULT 'debit';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS credit_limit DECIMAL(12, 2);
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS closing_day INT;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS due_day INT;

ALTER TABLE transactions ADD COLUMN IF NOT EXISTS paid BOOLEAN DEFAULT FALSE;
